import { ArrowDownRight, ArrowRight, Download } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';
import { profile } from '../../data/profile';
import { fadeUp, stagger } from '../../lib/motion';
import { Button } from '../ui/Button';
import { Container } from '../ui/Container';
import { SocialLinks } from '../ui/SocialLinks';

export function Hero() { const reduce = useReducedMotion(); return <section className="relative flex min-h-[92svh] items-center overflow-hidden pt-28"><div className="pointer-events-none absolute right-[-15%] top-24 size-[36rem] rounded-full bg-accent-500/[.08] blur-[100px]" /><Container><motion.div className="relative max-w-5xl" variants={reduce ? undefined : stagger} initial="hidden" animate="visible"><motion.div variants={reduce ? undefined : fadeUp} className="mb-7 inline-flex items-center gap-2 rounded-full border border-accent-400/20 bg-accent-400/[.06] px-4 py-2 text-xs font-semibold tracking-wide text-accent-300"><span className="size-2 rounded-full bg-accent-400" />{profile.availability}</motion.div><motion.p variants={reduce ? undefined : fadeUp} className="mb-5 text-sm font-bold uppercase tracking-[.22em] text-slate-400">Hi, I’m {profile.shortName}. <span className="text-accent-400">{profile.role}</span></motion.p><motion.h1 variants={reduce ? undefined : fadeUp} className="max-w-4xl text-balance text-5xl font-semibold leading-[.98] tracking-[-.055em] text-white sm:text-6xl md:text-7xl lg:text-[5.6rem]">{profile.headline}</motion.h1><motion.p variants={reduce ? undefined : fadeUp} className="mt-7 max-w-2xl text-pretty text-base leading-7 text-slate-400 sm:text-lg">{profile.bio}</motion.p><motion.div variants={reduce ? undefined : fadeUp} className="mt-9 flex flex-col gap-3 min-[430px]:flex-row"><Button href="#projects">View projects <ArrowDownRight size={18} /></Button>{profile.resumeUrl && <Button href={profile.resumeUrl} variant="secondary" download>Download resume <Download size={17} /></Button>}<Button href="#contact" variant="secondary">Let’s connect <ArrowRight size={17} /></Button></motion.div><motion.div variants={reduce ? undefined : fadeUp} className="mt-7"><SocialLinks /></motion.div></motion.div></Container></section>; }
